[tool.poetry]
name = "photo-django"
version = "0.1.0"
description = "PhotoShare.IO - share your photos with the world!"
authors = ["mmeerrccyy <taras.mercury@gmail.com>"]
readme = "README.md"
packages = [{include = "photo_django"}]

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.2.2"
djangorestframework = "^3.14.0"
graphene-django = "^3.1.1"
python-dotenv = "^1.0.0"
black = "^23.3.0"
psycopg2-binary = "^2.9.6"
pre-commit = "^3.3.2"
ariadne-django = "^0.3.0"


[tool.poetry.group.dev.dependencies]
mypy = "^1.3.0"
flake8 = "^6.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''