# Generated by Django 4.2.2 on 2024-04-22 13:43

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Title"),
                ),
                (
                    "content",
                    django_ckeditor_5.fields.CKEditor5Field(
                        verbose_name="Content"
                    ),
                ),
                (
                    "publish_datetime",
                    models.DateTimeField(verbose_name="Publish date"),
                ),
                (
                    "ready_to_publish",
                    models.BooleanField(
                        default=False, verbose_name="Ready to publish"
                    ),
                ),
            ],
        ),
    ]
