# Generated by Django 4.2.2 on 2024-04-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="celery_task",
            field=models.UUIDField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="Celery task",
            ),
        ),
    ]
